<a href="https://colab.research.google.com/github/annita049/Python-Django/blob/main/numpy_3darray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)
# arr3.ndim
# arr3.shape
# arr3.shape[0]

my_list = []

for i in range(arr3.shape[0]):
  for j in range(arr3.shape[1]):
    for k in range(arr3.shape[2]):
      my_list.append([arr3[i, j, k]])

print(my_list)
          # print(arr3[i, j, k])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12]]
